### ISSUE TITLE
user configurable defaults for ABOVEMAXCOLOR and BELOWMINCOLOR

### ISSUE THREAD

**Issue by pacioos** [Reading-eScience-Centre/ncwms#11]
Would be nice to have a way to specify a global default in THREDDS Data Server (TDS) wmsConfig.xml for the following ncWMS settings:

ABOVEMAXCOLOR=extend
BELOWMINCOLOR=extend

Would also be useful to adjust these settings at the datasetPath/pathDefaults level because I might want to change the above to "transparent" in some cases to override the global default.
Thanks!,
John Maurer
Pacific Islands Ocean Observing System (PacIOOS)

**Comment by lesserwhirls** [comment]
Hi @pacioos - my guess is this will need to be done on the TDS side of things. I referenced this issue in a new issue on the THREDDS project. Cheers!

**Comment by guygriffiths** [comment]
Yep, that's going to be a TDS configuration issue - @lesserwhirls, just ping me if you have any troubles with it.
