### ISSUE TITLE
Travis badge pointing to the wrong repo

### ISSUE THREAD

**Issue by kwilcox** [Reading-eScience-Centre/ncwms#14]
Can you enable https://travis-ci.org/Reading-eScience-Centre/ncwms and change the link on the Travis CI badge in the README? I can make the change once you enable travis on the repo.

**Comment by guygriffiths** [comment]
I think that's done.  I followed the link and clicked "Activate", then updated the links in the README.  All in the `develop` branch, so it'll make the next release
