### ISSUE TITLE
Setup automated Docker build on hub.docker.com

### ISSUE THREAD

**Issue by kwilcox** [Reading-eScience-Centre/ncwms#15]
There are a few references to the [axiom](https://hub.docker.com/r/axiom/ncwms/) docker container in the documentation. I'll fix them all if you enable the automated docker builds for this repo!

**Comment by guygriffiths** [comment]
I've enabled a build here: https://hub.docker.com/r/guygriffiths/ncwms/ but it's not working at the moment...

**Comment by guygriffiths** [comment]
Seems to be working with latest releases.  Closing.
