### ISSUE TITLE
Gridded Dataset Not Working

### ISSUE THREAD

**Issue by aj0415** [Reading-eScience-Centre/ncwms#2]
When I try to add a file with a gridded dataset through the admin page it gives me the following error: java.lang.NegativeArraySizeException. However, this same dataset works and is able to be displayed in NetCDF Tools UI, as well as Panoply. The file can be accessed from here: http://opendap.larc.nasa.gov/opendap/hyrax/.GIBS/CALIPSO/test_calipso.hdf.html

**Comment by guygriffiths** [comment]
This is due to the extreme dimensions of the grid you are using.  I have added a workaround for now, but it may result in inefficient plotting, so I will leave this issue open and try and investigate it further next week.  I will be doing a 2.2.3 release later today which will have the workaround in.

**Comment by aj0415** [comment]
Awesome, thank you!

**Comment by aj0415** [comment]
Were you able to actually load the file completely? I tried entering it in the admin page and it just loads forever and never finishes to even be able to try and request an image.

**Comment by guygriffiths** [comment]
I did manage to get it to load when I first made the fix, although it seems to be having trouble at the moment.  I'll look into it

**Comment by guygriffiths** [comment]
So this was due to an OutOfMemoryError which was being suppressed.  I've reduced the amount of memory that this sort of grid needs, as well as making sure that if it does run out of memory, it will report the error.

It's fixed in the develop branch

**Comment by aj0415** [comment]
Okay that great! Whats the best way to deploy this? I typically just download the war and upload to our server.

**Comment by guygriffiths** [comment]
I've put a build of the snapshot version up here:
http://www.personal.rdg.ac.uk/~qx901922/ncWMS2.war

No guarantees about how long it will stay there etc. (although I will probably leave it there until someone else wants a build of the latest development version)

**Comment by aj0415** [comment]
Thanks!
