### ISSUE TITLE
HTTP Status 500 - Servlet.init() for servlet NcwmsApplicationServlet threw exception

### ISSUE THREAD

**Issue by Abouzeid** [Reading-eScience-Centre/ncwms#28]
I am trying to run ncWMS2 on Tomcat but I am getting the error below

HTTP Status 500 - Servlet.init() for servlet NcwmsApplicationServlet threw exception

type Exception report

message Servlet.init() for servlet NcwmsApplicationServlet threw exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet.init() for servlet NcwmsApplicationServlet threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)

root cause

net.sf.ehcache.config.InvalidConfigurationException: There is one error in your configuration: 
	* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly

	net.sf.ehcache.config.CacheConfiguration.setupFor(CacheConfiguration.java:1694)
	net.sf.ehcache.config.CacheConfiguration.setupFor(CacheConfiguration.java:1678)
	net.sf.ehcache.CacheManager.initializeEhcache(CacheManager.java:1328)
	net.sf.ehcache.CacheManager.addCacheNoCheck(CacheManager.java:1399)
	net.sf.ehcache.CacheManager.addCache(CacheManager.java:1275)
	net.sf.ehcache.CacheManager.addCache(CacheManager.java:1244)
	uk.ac.rdg.resc.edal.catalogue.DataCatalogue.<init>(DataCatalogue.java:184)
	uk.ac.rdg.resc.edal.ncwms.NcwmsCatalogue.<init>(NcwmsCatalogue.java:82)
	uk.ac.rdg.resc.edal.ncwms.NcwmsApplicationServlet.init(NcwmsApplicationServlet.java:297)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.69 logs.

Any help will be appreciated.

**Comment by guygriffiths** [comment]
The problem is that ncWMS uses a cache to store features, but it is requesting more memory than you have allocated the JVM.  The best thing to do would be to increase the memory available to the JVM:

https://stackoverflow.com/questions/35367218/how-to-increase-jvm-memory-on-tomcat-8

(this should work equally well for Tomcat 7).

It should also be possible to configure the cache size (or turn it off) from the `.ncWMS/config.xml` file, but if this is the first time you've run it, that file may not have been created.

It would also be useful if you could let me know which version of ncWMS you are running, and on what operating system - it may be useful for me to change the defaults to avoid this issue in future.

**Comment by Abouzeid** [comment]
Spec: 
- OS: Centos 7 
- ncWMS 2.4.0
- Servlet Container: Apache Tomcat/7.0.69

I did add the **setenv.sh** file to the /bin directory but I've got the same error. I will try to upgrade to Tomcat 8 and see.

**Comment by Abouzeid** [comment]
NcWMS2 works as expected on Apache Tomcat 8.5.30. Now, I am closing this issue. Thank you Griffiths for your answer.
