### ISSUE TITLE
missing geotoolkit driver when hosting ncWMS on Linux

### ISSUE THREAD

**Issue by matthijslemans** [Reading-eScience-Centre/ncwms#32]
Hello,

I am hosting a ncWMS in a Tomcat servlet container on Linux, but when trying to query the data from a mapbox/leaflet environment (with openstreetmaps=espg:3857 ), I get the error below.

The CRS EPSG:3857 is not supported by this server 
       Cause: 
           Authority “EPSG” is not available. The cause is: No suitable driver found for jdbc:derby:/usr/share/tomcat/.geotoolkit.org/EPSG/7.09;create=true  

When hosting on Windows, it works fine, after deploying I automatically get an
embedded database in a .h2 subdir that stores the EPSG dataset to perform coordinate transformations.
In the tomcat logs on windows I see indeed a reference to this:
org.geotoolkit.referencing.factory.epsg.ThreadedEpsgFactory createBackingStore
INFO: Connected to EPSG database “jdbc:h2:c:\Program Files\Apache Software Foundation\ncWMS_Covadem/.h2/epsg.db” on “H2”

However, on Linux somehow this part is missing. The folder tomcat/.geotoolkit.org is empty.
I am using the most recent ncWMS2.war from the internet, and tomcat7.

Any thoughts on what I might do wrong?

**Comment by guygriffiths** [comment]
That's rather strange - the H2 database is specifically used, so there is no reason why it should be searching for a Derby database.  I suspect that it might be that the H2 db creation is failing.  Can you enable the DEBUG log level for `uk.ac.rdg.resc.edal.util.GISUtils` and re-run?  That should give some more information in the logs.

One possibility is that you are running as a `tomcat` user on Linux which doesn't have write access to its own home directory, or has no home directory defined.

**Comment by matthijslemans** [comment]
Hi guy
Indeed i run as tomcat user on linux. It should have write permissions to
its own home dir, but will double check, and enable the debug you mentioned.

Thanks
Matthijs


Op di 5 jun. 2018 16:10 schreef Guy Griffiths <notifications@github.com>:

**Comment by matthijslemans** [comment]
issue was solved, indeed there was one file somewhere with incorrect user
