### ISSUE TITLE
Fail to read NetCDF-4/HDF-5 CF-1.4

### ISSUE THREAD

**Issue by ZihengSun** [Reading-eScience-Centre/ncwms#36]
I am trying to load netCDF4 data into ncWMS. The following error pops up:

> uk.ac.rdg.resc.edal.exceptions.EdalException: Problem creating dataset 3dh0locu at D:/work/TESTDATA/earthcube//asr15km.anl.2D.201602.mon.nc
> 	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:115)
> 	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:1)
> 	at uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.createDataset(DatasetConfig.java:254)
> 	at uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.refresh(DatasetConfig.java:213)
> 	at uk.ac.rdg.resc.edal.catalogue.jaxb.CatalogueConfig$1.run(CatalogueConfig.java:154)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: uk.ac.rdg.resc.edal.exceptions.DataReadingException: No grids found in underlying NetCDF dataset
> 	at uk.ac.rdg.resc.edal.util.cdm.CdmUtils.getGridDataset(CdmUtils.java:123)
> 	at uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.getNonStaggeredGriddedVariableMetadata(CdmGridDatasetFactory.java:143)
> 	at uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.generateGridDataset(CdmGridDatasetFactory.java:134)
> 	at uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.generateDataset(CdmGridDatasetFactory.java:124)
> 	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:88)
> 	... 11 more

It has no problem loading netCDF3 CF-1.0. I suppose CF-1.4 or NetCDF-4 is not supported by EDAL? These two formats are in the support list of [netCDF-Java](https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/formats/FileTypes.html).

**Comment by guygriffiths** [comment]
That error is usually caused when the coordinate axes are not well defined (according to CF conventions) or there is no gridded data in the NetCDF.  If you can send me a sample of the data, or just the headers (as seen by `ncdump -h <file.nc>` I can probably tell you what's going wrong.

**Comment by ZihengSun** [comment]
Hi Guy, thank you for replying. The netcdf can be downloaded from here. The following is its ncdump metadata:

> netcdf asr15km.anl.2D.200001.mon {
> dimensions:
>         time = UNLIMITED ; // (1 currently)
>         time = UNLIMITED ; // (1 currently)
>         y = 720 ;
>         x = 720 ;
>         lev = 4 ;
> variables:
>         int DateTime(time) ;
>                 DateTime:long_name = "Date and Time" ;
>                 DateTime:units = "1" ;
>         int Time(time) ;
>                 Time:long_name = "time" ;
>                 Time:units = "hours since 1901-01-01 00:00:00" ;
>         float ALBBCK(time, y, x) ;
>                 ALBBCK:units = "1.0" ;
>                 ALBBCK:coordinates = "XLONG XLAT" ;
>                 ALBBCK:FieldType = 104 ;
>                 ALBBCK:MemoryOrder = "XY " ;
>                 ALBBCK:description = "BACKGROUND ALBEDO" ;
>                 ALBBCK:stagger = "" ;
>         float ALBEDO(time, y, x) ;
>                 ALBEDO:units = "1.0" ;
>                 ALBEDO:coordinates = "XLONG XLAT" ;
>                 ALBEDO:FieldType = 104 ;
>                 ALBEDO:MemoryOrder = "XY " ;
>                 ALBEDO:description = "ALBEDO" ;
>                 ALBEDO:stagger = "" ;
>         float ALBSI(time, y, x) ;
>                 ALBSI:units = "1.0" ;
>                 ALBSI:coordinates = "XLONG XLAT" ;
>                 ALBSI:FieldType = 104 ;
>                 ALBSI:MemoryOrder = "XY " ;
>                 ALBSI:description = "ALBEDO OF SEA ICE" ;
>                 ALBSI:stagger = "" ;
>         float ICEDEPTH(time, y, x) ;
>                 ICEDEPTH:units = "m" ;
>                 ICEDEPTH:coordinates = "XLONG XLAT" ;
>                 ICEDEPTH:FieldType = 104 ;
>                 ICEDEPTH:MemoryOrder = "XY " ;
>                 ICEDEPTH:description = "SEA ICE THICKNESS" ;
>                 ICEDEPTH:stagger = "" ;
>         int ISLTYP(time, y, x) ;
>                 ISLTYP:units = "1" ;
>                 ISLTYP:coordinates = "XLONG XLAT" ;
>                 ISLTYP:FieldType = 106 ;
>                 ISLTYP:MemoryOrder = "XY " ;
>                 ISLTYP:description = "DOMINANT SOIL CATEGORY" ;
>                 ISLTYP:stagger = "" ;
>         int IVGTYP(time, y, x) ;
>                 IVGTYP:units = "1" ;
>                 IVGTYP:coordinates = "XLONG XLAT" ;
>                 IVGTYP:FieldType = 106 ;
>                 IVGTYP:MemoryOrder = "XY " ;
>                 IVGTYP:description = "DOMINANT VEGETATION CATEGORY" ;
>                 IVGTYP:stagger = "" ;
>         float LAI(time, y, x) ;
>                 LAI:units = "area/area" ;
>                 LAI:coordinates = "XLONG XLAT" ;
>                 LAI:FieldType = 104 ;
>                 LAI:MemoryOrder = "XY " ;
>                 LAI:description = "Leaf area index" ;
>                 LAI:stagger = "" ;
>         float LANDMASK(time, y, x) ;
>                 LANDMASK:units = "1" ;
>                 LANDMASK:coordinates = "XLONG XLAT" ;
>                 LANDMASK:FieldType = 104 ;
>                 LANDMASK:MemoryOrder = "XY " ;
>                 LANDMASK:description = "LAND MASK (1 FOR LAND, 0 FOR WATER)" ;
>                 LANDMASK:stagger = "" ;
>         float LU_INDEX(time, y, x) ;
>                 LU_INDEX:units = "1" ;
>                 LU_INDEX:coordinates = "XLONG XLAT" ;
>                 LU_INDEX:FieldType = 104 ;
>                 LU_INDEX:MemoryOrder = "XY " ;
>                 LU_INDEX:description = "LAND USE CATEGORY" ;
>                 LU_INDEX:stagger = "" ;
>         float PMSL(time, y, x) ;
>                 PMSL:units = "Pa" ;
>                 PMSL:coordinates = "XLONG XLAT" ;
>                 PMSL:FieldType = 104 ;
>                 PMSL:MemoryOrder = "XYZ" ;
>                 PMSL:description = "Sea-level Pressure" ;
>                 PMSL:stagger = "-" ;
>         float PSFC(time, y, x) ;
>                 PSFC:units = "Pa" ;
>                 PSFC:coordinates = "XLONG XLAT" ;
>                 PSFC:FieldType = 104 ;
>                 PSFC:MemoryOrder = "XY " ;
>                 PSFC:description = "SFC PRESSURE" ;
>                 PSFC:stagger = "" ;
>         float Q2M(time, y, x) ;
>                 Q2M:units = "kg kg-1" ;
>                 Q2M:coordinates = "XLONG XLAT" ;
>                 Q2M:FieldType = 104 ;
>                 Q2M:MemoryOrder = "XYZ" ;
>                 Q2M:description = "QV at 2 M" ;
>                 Q2M:stagger = "-" ;
>         float RH2M(time, y, x) ;
>                 RH2M:units = "%" ;
>                 RH2M:coordinates = "XLONG XLAT" ;
>                 RH2M:FieldType = 104 ;
>                 RH2M:MemoryOrder = "XYZ" ;
>                 RH2M:description = "Relative Humidity at 2 M" ;
>                 RH2M:stagger = "-" ;
>         float SEAICE(time, y, x) ;
>                 SEAICE:units = "1.0" ;
>                 SEAICE:coordinates = "XLONG XLAT" ;
>                 SEAICE:FieldType = 104 ;
>                 SEAICE:MemoryOrder = "XY " ;
>                 SEAICE:description = "SEA ICE FLAG" ;
>                 SEAICE:stagger = "" ;
>         float SH2O(time, lev, y, x) ;
>                 SH2O:units = "m3 m-3" ;
>                 SH2O:coordinates = "XLONG XLAT" ;
>                 SH2O:FieldType = 104 ;
>                 SH2O:MemoryOrder = "XYZ" ;
>                 SH2O:description = "SOIL LIQUID WATER" ;
>                 SH2O:stagger = "Z" ;
>         float SKINTEMP(time, y, x) ;
>                 SKINTEMP:units = "K" ;
>                 SKINTEMP:coordinates = "XLONG XLAT" ;
>                 SKINTEMP:FieldType = 104 ;
>                 SKINTEMP:MemoryOrder = "XY " ;
>                 SKINTEMP:description = "SURFACE SKIN TEMPERATURE" ;
>                 SKINTEMP:stagger = "" ;
>         float SMOIS(time, lev, y, x) ;
>                 SMOIS:units = "m3 m-3" ;
>                 SMOIS:coordinates = "XLONG XLAT" ;
>                 SMOIS:FieldType = 104 ;
>                 SMOIS:MemoryOrder = "XYZ" ;
>                 SMOIS:description = "SOIL MOISTURE" ;
>                 SMOIS:stagger = "Z" ;
>         float SNOALB(time, y, x) ;
>                 SNOALB:units = "1.0" ;
>                 SNOALB:coordinates = "XLONG XLAT" ;
>                 SNOALB:FieldType = 104 ;
>                 SNOALB:MemoryOrder = "XY " ;
>                 SNOALB:description = "ANNUAL MAX SNOW ALBEDO IN FRACTION" ;
>                 SNOALB:stagger = "" ;
>         float SNOW(time, y, x) ;
>                 SNOW:units = "kg m-2" ;
>                 SNOW:coordinates = "XLONG XLAT" ;
>                 SNOW:FieldType = 104 ;
>                 SNOW:MemoryOrder = "XY " ;
>                 SNOW:description = "SNOW WATER EQUIVALENT" ;
>                 SNOW:stagger = "" ;
>         float SNOWC(time, y, x) ;
>                 SNOWC:units = "1.0" ;
>                 SNOWC:coordinates = "XLONG XLAT" ;
>                 SNOWC:FieldType = 104 ;
>                 SNOWC:MemoryOrder = "XY " ;
>                 SNOWC:description = "FLAG INDICATING SNOW COVERAGE (1 FOR SNOW COVER)" ;
>                 SNOWC:stagger = "" ;
>         float SNOWH(time, y, x) ;
>                 SNOWH:units = "m" ;
>                 SNOWH:coordinates = "XLONG XLAT" ;
>                 SNOWH:FieldType = 104 ;
>                 SNOWH:MemoryOrder = "XY " ;
>                 SNOWH:description = "PHYSICAL SNOW DEPTH" ;
>                 SNOWH:stagger = "" ;
>         float SST(time, y, x) ;
>                 SST:units = "K" ;
>                 SST:coordinates = "XLONG XLAT" ;
>                 SST:FieldType = 104 ;
>                 SST:MemoryOrder = "XY " ;
>                 SST:description = "SEA SURFACE TEMPERATURE" ;
>                 SST:stagger = "" ;
>         float T2M(time, y, x) ;
>                 T2M:units = "K" ;
>                 T2M:coordinates = "XLONG XLAT" ;
>                 T2M:FieldType = 104 ;
>                 T2M:MemoryOrder = "XYZ" ;
>                 T2M:description = "TEMP at 2 M" ;
>                 T2M:stagger = "-" ;
>         float TSLB(time, lev, y, x) ;
>                 TSLB:units = "K" ;
>                 TSLB:coordinates = "XLONG XLAT" ;
>                 TSLB:FieldType = 104 ;
>                 TSLB:MemoryOrder = "XYZ" ;
>                 TSLB:description = "SOIL TEMPERATURE" ;
>                 TSLB:stagger = "Z" ;
>         float U10E(time, y, x) ;
>                 U10E:units = "m s-1" ;
>                 U10E:coordinates = "XLONG XLAT" ;
>                 U10E:FieldType = 104 ;
>                 U10E:MemoryOrder = "XYZ" ;
>                 U10E:description = "Earth-relative zonal wind at 10 M" ;
>                 U10E:stagger = "-" ;
>         float U10M(time, y, x) ;
>                 U10M:units = "m s-1" ;
>                 U10M:coordinates = "XLONG XLAT" ;
>                 U10M:FieldType = 104 ;
>                 U10M:MemoryOrder = "XYZ" ;
>                 U10M:description = "x-grid relative wind conponent at 10 M" ;
>                 U10M:stagger = "-" ;
>         float V10E(time, y, x) ;
>                 V10E:units = "m s-1" ;
>                 V10E:coordinates = "XLONG XLAT" ;
>                 V10E:FieldType = 104 ;
>                 V10E:MemoryOrder = "XYZ" ;
>                 V10E:description = "Earth-relative meridional wind at 10 M" ;
>                 V10E:stagger = "-" ;
>         float V10M(time, y, x) ;
>                 V10M:units = "m s-1" ;
>                 V10M:coordinates = "XLONG XLAT" ;
>                 V10M:FieldType = 104 ;
>                 V10M:MemoryOrder = "XYZ" ;
>                 V10M:description = "y-grid relative wind conponent at 10 M" ;
>                 V10M:stagger = "-" ;
>         float VEGFRA(time, y, x) ;
>                 VEGFRA:units = "%" ;
>                 VEGFRA:coordinates = "XLONG XLAT" ;
>                 VEGFRA:FieldType = 104 ;
>                 VEGFRA:MemoryOrder = "XY " ;
>                 VEGFRA:description = "VEGETATION FRACTION" ;
>                 VEGFRA:stagger = "" ;
>         float XLAT(y, x) ;
>                 XLAT:standard_name = "latitude" ;
>                 XLAT:long_name = "latitude" ;
>                 XLAT:units = "degree_north" ;
>                 XLAT:_CoordinateAxisType = "Lat" ;
>         float XLONG(y, x) ;
>                 XLONG:standard_name = "longitude" ;
>                 XLONG:long_name = "longitude" ;
>                 XLONG:units = "degree_east" ;
>                 XLONG:_CoordinateAxisType = "Lon" ;
>         double lev(lev) ;
>                 lev:long_name = "generic" ;
>                 lev:units = "level" ;
>                 lev:axis = "Z" ;
> 
> // global attributes:
>                 :CDI = "Climate Data Interface version 1.5.4 (http://code.zmaw.de/projects/cdi)" ;
>                 :Conventions = "CF-1.4" ;
>                 :TITLE = "Arctic System Reanalysis - The Ohio State Univresity, Polar Meteorology Group" ;
>                 :WEST-EAST_GRID_DIMENSION = 721 ;
>                 :SOUTH-NORTH_GRID_DIMENSION = 721 ;
>                 :BOTTOM-TOP_GRID_DIMENSION = 34 ;
>                 :GRIDTYPE = "C" ;
>                 :DIFF_OPT = 1 ;
>                 :KM_OPT = 1 ;
>                 :DAMP_OPT = 0 ;
>                 :MP_PHYSICS = 7 ;
>                 :RA_LW_PHYSICS = 0 ;
>                 :RA_SW_PHYSICS = 0 ;
>                 :SF_SFCLAY_PHYSICS = 5 ;
>                 :SF_SURFACE_PHYSICS = 2 ;
>                 :BL_PBL_PHYSICS = 1 ;
>                 :CU_PHYSICS = 1 ;
>                 :SURFACE_INPUT_SOURCE = 1 ;
>                 :SST_UPDATE = 0 ;
>                 :GRID_FDDA = 0 ;
>                 :GFDDA_INTERVAL_M = 0 ;
>                 :GFDDA_END_H = 0 ;
>                 :GRID_SFDDA = 0 ;
>                 :SGFDDA_INTERVAL_M = 0 ;
>                 :SGFDDA_END_H = 0 ;
>                 :HYPSOMETRIC_OPT = 1 ;
>                 :WEST-EAST_PATCH_START_UNSTAG = 1 ;
>                 :WEST-EAST_PATCH_END_UNSTAG = 720 ;
>                 :WEST-EAST_PATCH_START_STAG = 1 ;
>                 :WEST-EAST_PATCH_END_STAG = 721 ;
>                 :SOUTH-NORTH_PATCH_START_UNSTAG = 1 ;
>                 :SOUTH-NORTH_PATCH_END_UNSTAG = 720 ;
>                 :SOUTH-NORTH_PATCH_START_STAG = 1 ;
>                 :SOUTH-NORTH_PATCH_END_STAG = 721 ;
>                 :GRID_ID = 1 ;
>                 :PARENT_ID = 0 ;
>                 :PARENT_GRID_RATIO = 1 ;
>                 :MAP_PROJ = 2 ;
>                 :MMINLU = "MODIFIED_IGBP_MODIS_NOAH" ;
>                 :NUM_LAND_CAT = 20 ;
>                 :ISWATER = 17 ;
>                 :ISLAKE = -1 ;
>                 :ISICE = 15 ;
>                 :ISURBAN = 13 ;
>                 :ISOILWATER = 14 ;
>                 :I_PARENT_START = 1 ;
>                 :J_PARENT_START = 1 ;
>                 :IFNDALBSI = 1 ;
>                 :IFNDICEDEPTH = 1 ;
>                 :IFNDSNOWSI = 1 ;
>                 :CDO = "Climate Data Operators version 1.5.4 (http://code.zmaw.de/projects/cdo)" ;
>                 :history = "Wed Mar 15 21:08:02 2017: ./ncks -C -O -x -v time,DateTime anl.sfc200001 ../../../MonthlyMean/asr15km.anl.2D.200001.mon" ;
>                 :NCO = "4.2.1" ;
> }

The data is from the Arctic System Reanalysis dataset, downloaded from the [research data archive of UCAR](https://rda.ucar.edu/datasets/ds631.1/).

**Comment by guygriffiths** [comment]
Your time axis doesn't have a coordinate variable.  Rename the variable `Time` to `time` and it will work.
