### ISSUE TITLE
Odd behavior in Godiva3 map when changing between unstructured grids

### ISSUE THREAD

**Issue by marceloandrioni** [Reading-eScience-Centre/ncwms#46]
Hello, when choosing different model results in Godiva3 I noticed some odd behavior when dealing with unstructured grids. The steps to reproduce the problem are:

1) choosing the first model (adcirc_tabg_t1) the grid (barotropic uv) is displayed correctly.
2) after choosing the second model (adcirc_tebig_t1), instead of changing the displayed area to that of the second model (or not changing the area but instead just erasing the grid of the first model) the first model is still displayed, but incorrectly.
3) after pressing the "Fit the map to this layer's extents" button the second model is displayed correctly.

The files used in the test are here: [ugrids.zip](https://github.com/Reading-eScience-Centre/ncwms/files/3602602/ugrids.zip)

Thank you.

![image 1](https://user-images.githubusercontent.com/13545615/64732808-ddfe9c80-d4b9-11e9-9fb9-3399173e1c91.png)
![image 2](https://user-images.githubusercontent.com/13545615/64732809-ddfe9c80-d4b9-11e9-9b37-61c774310d22.png)
![image 3](https://user-images.githubusercontent.com/13545615/64732810-ddfe9c80-d4b9-11e9-9e03-37cc1bb3d018.png)

System:
ncWMS v2.4.1
Apache Tomcat/8.5.45
Linux x86_64 Kernel 4.15.0-58-generic

**Comment by guygriffiths** [comment]
Thanks for pointing this one out.  I don't have very much time available for ncWMS development, but I've managed to fix this in the `develop` branch.  I've got a couple more bugs I want to get around to today, then I'll make a v2.4.2 release, hopefully tomorrow.
