### ISSUE TITLE
GetTimeseries/GetVerticalProfile documentation is difficult to understand

### ISSUE THREAD

**Issue by juozasg** [Reading-eScience-Centre/ncwms#50]
I'm struggling to understand how the BBOX, X, Y, WIDTH and HEIGHT parameters are used together to in GetTimeseries and GetVerticalProfile queries. Can you include some examples in the documentation or more details on the semantics of these parameters, please?

**Comment by guygriffiths** [comment]
They indicate a point in exactly the same way as those in GetFeatureInfo requests.  The idea is that a client can simply reuse the parameters from a GetFeatureInfo request to generate a timeseries/profile plot at the same point.

**Comment by juozasg** [comment]
This is the source of my confusion. In GetFeatureInfo, the parameters  HEIGHT and WIDTH define the output image size. But for GetTimeseries and GetVerticalProfile the documentation says

> the parameters CHARTWIDTH and CHARTHEIGHT specify the output size of the graph - note that the HEIGHT and WIDTH parameters define the location

I don't understand how HEIGHT and WIDTH define the location?

**Comment by guygriffiths** [comment]
>  In GetFeatureInfo, the parameters HEIGHT and WIDTH define the output image size.

This is incorrect, GetFeatureInfo does not generate an output image.

A combination of the parameters `HEIGHT`, `WIDTH`, `BBOX`, `X`, and `Y` (or `I` and `J` depending on WMS version) define the **_location_** of a GetFeatureInfo request.  The same is true of GetTimeseries and GetVerticalProfile.

i.e. In an image which maps a `BBOX` to a grid of size `WIDTH`*`HEIGHT`, choose the location which corresponds to the pixel at (`X`, `Y`).

**Comment by juozasg** [comment]
Thank you!!
