### ISSUE TITLE
GetMap returns "HTTP Status 500 - java.lang.NullPointerException"

### ISSUE THREAD

**Issue by Abouzeid** [Reading-eScience-Centre/ncwms#58]
When I disable either the **Dynamic Service cache** or the **ncWMS Cache**, the **GetMap** request returns a NullPointerException.
I'd like to disable the Dynamic service cache as the datasets change regularly. Also, is there any recommended on the maximum number of datasets ncWMS could have.

- ncWMS v2.4.2

Thanks a lot in advance.
Any help will be appreciated.

![image](https://user-images.githubusercontent.com/9715386/85256386-b865e100-b496-11ea-8777-00eb4797784f.png)

**Comment by guygriffiths** [comment]
Thanks for pointing this out.  I've just fixed it so it'll be in the next release.  For the time being I would recommend setting the cache element timeout to a low number.  It's specified in minutes and accepts floating points.  0 is "never expire", so it needs to be >0.

**Comment by Abouzeid** [comment]
Understood thanks @guygriffiths  for your reply.
