### ISSUE TITLE
Dynamic color palette for GetMap extensions

### ISSUE THREAD

**Issue by dev-oups** [Reading-eScience-Centre/ncwms#59]
Is it possible to add a new variable to be able to use a dynamic color palette?

For now I must use the `STYLES` variable to use an existing "dynamic palette" from the geoserver.

Thanks.

**Comment by guygriffiths** [comment]
You can specify something like `STYLES=default-scalar/0x000000:0xff0000:0x00ff00` in the URL, and that will generate a palette on-the-fly.  Colours can be 0xRRGGBB or 0xAARRGGBB if you want transparency.  It will interpolate evenly between all specified colours, up to `NUMCOLORBANDS`.  Does that work for what you want?

**Comment by dev-oups** [comment]
Thanks this is what I want but I get the following error "No such style: default-scalar/0x000000:0xff0000:0x00ff00".

I use the geoserver version 2.17.0

**Comment by guygriffiths** [comment]
Ah, sorry, I think you might have your wires crossed.  Are you just using Geoserver?  ncWMS is an unrelated project.  I know that Geoserver have implemented some of the extensions we've created (see https://docs.geoserver.org/latest/en/user/community/ncwms/index.html), but it's a completely separate project.

**Comment by dev-oups** [comment]
I use geoserver with the ncWMS extension. (the `COLORSCALERANGE` variable is working)

I did not understood if this is possible with this configuration or not.

**Comment by guygriffiths** [comment]
> I use geoserver with the ncWMS extension.
In that case I'm afraid I can't help.  I'm not sure how much of our code they use, but it's not an extension that we've been involved with at all.
