### ISSUE TITLE
getlegendgraphic must have LAYERS even if only single layer being displayed

### ISSUE THREAD

**Issue by scaddenp** [Reading-eScience-Centre/ncwms#65]
Minor detail. Docs and error message say you could use LAYER and STYLE for single layer. However, while STYLE or STYLES both work, you must have LAYERS not LAYER

**Comment by guygriffiths** [comment]
Have you got an example of this?  LAYER works on the examples I've tried.

**Comment by scaddenp** [comment]
Interesting. I lodged this when working with Thredds beta. Plain LAYER is working for me too on the develop branch.
