### ISSUE TITLE
How to run source code？

### ISSUE THREAD

**Issue by 7757** [Reading-eScience-Centre/ncwms#69]
Recently, I'm trying to clone your code on git, but I can't find the main entrance of the program in idea. I need you to help me. Thank you very much.

**Comment by guygriffiths** [comment]
ncWMS runs as Java servlet on a servlet engine (usually Tomcat).  The servlet entry points and the URLs which map to them are defined in https://github.com/Reading-eScience-Centre/ncwms/blob/master/src/main/webapp/WEB-INF/web.xml

If you are not familiar with writing servlets, I would recommend looking at some simple tutorials first - ncWMS is a fairly complex application.

**Comment by 7757** [comment]
In fact, my main purpose in running this program is: 1 to understand how ncwms works, 2 how to resolve the netcdf structure of the file, 3 how to publish this data into the wms service. I come from China, English is not very good, I hope you can forgive me not very good English, you would like to help me answer, through the form of text plus code, thank you very much.

**Comment by guygriffiths** [comment]
Thanks for getting in touch.  I apologise, but I do not have the time for the kind of detailed help you will need.  I recommend learning about Java servlets, and then looking at the ncWMS source code, starting from the classes listed in https://github.com/Reading-eScience-Centre/ncwms/blob/master/src/main/webapp/WEB-INF/web.xml

**Comment by 7757** [comment]
Well, I see, thank you very much for your answer, and ncwms is a great program, I hope you have a good life.
