### ISSUE TITLE
Null pointer exception when using dynamic services in ncwms 2.2.7

### ISSUE THREAD

**Issue by cehbrecht** [Reading-eScience-Centre/ncwms#7]
I've configured dynamic services and call it like this:

    http://localhost:8080/ncWMS2/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0&DATASET=cache/test.nc

It seems to find the dataset id but i get an exception (worked before at least in 2.2.5):

```
java.lang.NullPointerException
	uk.ac.rdg.resc.edal.ncwms.NcwmsCatalogue.getDatasetFromId(NcwmsCatalogue.java:157)
	uk.ac.rdg.resc.edal.wms.WmsServlet.getCapabilities(WmsServlet.java:673)
	uk.ac.rdg.resc.edal.wms.WmsServlet.dispatchWmsRequest(WmsServlet.java:359)
	uk.ac.rdg.resc.edal.ncwms.NcwmsServlet.dispatchWmsRequest(NcwmsServlet.java:210)
	uk.ac.rdg.resc.edal.wms.WmsServlet.doGet(WmsServlet.java:292)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

Its running on tomcat 7.0.63 and openjdk 8.0.121

**Comment by guygriffiths** [comment]
I've just pushed a workaround to the develop branch.

@yosoyjay - This is related to the new caching stuff, where the dynamic dataset cache is null - is there a config file workaround to this?

**Comment by yosoyjay** [comment]
Yup, it's not defined without specifying a path to an ehcache.xml file with a definition for dynamicDatasetCache.

I created [PR](https://github.com/Reading-eScience-Centre/ncwms/pull/8) so that a default dynamicDatasetCache is created as was the case before if a users doesn't supply a ehcache.xml file.

**Comment by cehbrecht** [comment]
i've updated to ncwms 2.2.8 and the dynamic service works again.
