### ISSUE TITLE
Version 2.5.0 not running on Java 8 

### ISSUE THREAD

**Issue by MarcoAlbaETT** [Reading-eScience-Centre/ncwms#70]
Hi,
the last release does not work with Java 8, is the change intentional?

thanks

Marco

**Comment by marceloandrioni** [comment]
Hello @MarcoAlbaETT , I made the same question [here](https://github.com/Reading-eScience-Centre/edal-java/issues/132#issuecomment-697477916) and @guygriffiths confirmed that v2.5 will only run in Java (JDK) 11.

**Comment by MarcoAlbaETT** [comment]
Thanks @marceloandrioni !
Since I can't use Java 11, I'll make a custom version in order to be able to use java 8.

**Comment by ghansham** [comment]
Before 2.5.0 got released, I was using development branch and was able to
run it with jdk8. You can try openjdk 11 also. Just change the main pom to
have target version as jdk8. It should get compiled.
