### ISSUE TITLE
Feature Request: data of 1-dimension

### ISSUE THREAD

**Issue by john-jinghai-ma** [Reading-eScience-Centre/ncwms#75]
We have 1-dimension data from a stream flow model. It would be great if ncWMS can process it.

**Comment by guygriffiths** [comment]
I'm not familiar with stream flow models, what sort of map would it be able to generate?

**Comment by john-jinghai-ma** [comment]
Had a chat with domain experts in my team, it seems that 1-D and map do not really go together. So withdraw this feature request.
