### ISSUE TITLE
Can I remove the layer name in the result legend of getLegendGraphic?

### ISSUE THREAD

**Issue by nuds-zhao** [Reading-eScience-Centre/ncwms#79]
Hi, the legend returned by getLegendGraphic always has a layername on it. How can I remove it?

![image](https://user-images.githubusercontent.com/38685062/104646052-f1a5ae80-567d-11eb-8375-3661e6c1f62c.png)

**Comment by guygriffiths** [comment]
You can't just remove the label, but you can provide `COLORBARONLY=true` to just generate the colour bar, then use that to create your own legend.
