### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by vasconde** [Reading-eScience-Centre/ncwms#84]
When I try to build the docker image using the Dockerfile I'm getting the following error:

`

 => ERROR [3/7] RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main\ndeb-src http://ppa.la  8.7s
------
 > [3/7] RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main\ndeb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/webupd8team-java.list &&      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 &&      apt-get update &&      echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections &&      echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections &&      apt-get install -y oracle-java8-installer &&      update-java-alternatives -s java-8-oracle &&      export JAVA_HOME=/usr/lib/jvm/java-8-oracle:
#5 0.887 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#5 0.959 Executing: /tmp/apt-key-gpghome.hGfQO8yHsy/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
#5 1.541 gpg: key 8F9293A1EEA14886: public key "Totally Legit Signing Key <mallory@example.org>" imported
#5 1.549 gpg: Total number processed: 1
#5 1.549 gpg:               imported: 1
#5 2.378 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#5 2.380 Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#5 2.447 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#5 2.634 Get:4 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.6 kB]
#5 2.705 Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [72.0 kB]
#5 2.931 Get:6 http://deb.debian.org/debian bullseye/main amd64 Packages [8180 kB]
#5 3.615 Err:4 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
#5 3.615   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
#5 5.065 Get:7 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2300 B]
#5 6.859 Reading package lists...
#5 8.498 W: GPG error: http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C2518248EEA14886
#5 8.498 E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease' is not signed.
------
executor failed running [/bin/sh -c echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main\ndeb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" > /etc/apt/sources.list.d/webupd8team-java.list &&      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 &&      apt-get update &&      echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections &&      echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections &&      apt-get install -y oracle-java8-installer &&      update-java-alternatives -s java-8-oracle &&      export JAVA_HOME=/usr/lib/jvm/java-8-oracle]: exit code: 100

`

**Comment by guygriffiths** [comment]
Ok, I think I've fixed this on the `develop` branch.  Give it a go and let me know if you run into any issues.

**Comment by vasconde** [comment]
Now I tried using the develop branch.
I'm getting the following:
![image](https://user-images.githubusercontent.com/1152065/150516251-7f3c777b-9a3b-4d34-9cd0-71aff8f0d12d.png)

**Comment by guygriffiths** [comment]
Hmm, not sure about this, I couldn't reproduce it.  I've bumped the log4j version (which needed doing anyway), does that change anything for you?

**Comment by vasconde** [comment]
@guygriffiths now it's building without issues.
Thks
