### ISSUE TITLE
Horizontal Colorbars?

### ISSUE THREAD

**Issue by jbzambon** [Reading-eScience-Centre/ncwms#88]
Is it possible to have horizontal colorbars? I've tried several options that don't seem to work in the WMS requests...

`&LEGEND_OPTIONS=layout:horizontal`

The closest I've gotten is using `colorbaronly=true` but then there are no values to associate with the colorbar.

`http://localhost:8080/ncWMS2/wms?request=GetLegendGraphic&height=100&width=800&numcolorbands=250&colorbaronly=true&vertical=false&palette=default`

Setting colorbaronly to false gives me the following error

`You must specify either SLD, SLD_BODY, LAYERS and STYLES, or LAYER and STYLE for a full legend. You may set COLORBARONLY=true to just generate a colour bar`

Setting these parameters overrides the vertical=false flag somehow?

`http://localhost:8080/ncWMS2/wms?REQUEST=GetLegendGraphic&height=100&width=800&numcolorbands=250&vertical=false&palette=default&LAYERS=0/v&STYLES=default-scalar/default`

Thanks in advance!

**Comment by guygriffiths** [comment]
Sorry, no, it's possible to generate a colourbar in either orientation, but the full legend with labels etc. is only available in vertical orientation.

**Comment by ghansham** [comment]
I modified the codebase to try this:
See these links:

Horizontal Orientation:
https://rapid.imd.gov.in/r2wms/wms?&request=GetLegendGraphic&style=default/insat_brt&COLORSCALERANGE=185,365&WIDTH=20&HEIGHT=350&LAYERS=3DIMG_L1B_STD4/IMG_TIR1_TEMP2D&BELOWMINCOLOR=extend&ABOVEMAXCOLOR=extend&vertical=false

Vertical Orientation:
https://rapid.imd.gov.in/r2wms/wms?&request=GetLegendGraphic&style=default/insat_brt&COLORSCALERANGE=185,365&WIDTH=20&HEIGHT=350&LAYERS=3DIMG_L1B_STD4/IMG_TIR1_TEMP2D&BELOWMINCOLOR=extend&ABOVEMAXCOLOR=extend&vertical=true

This works for single band datasets at least.

regards
Ghansham

**Comment by jbzambon** [comment]
Thanks much, @ghansham and @guygriffiths!  Feel free to close this out.
